# Generated by kpex 0.2.5
crashbackups stop
drc off
gds read /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/gds/pll_3bitDiv.gds
load pll_3bitDiv
select top cell
flatten pll_3bitDiv_flat
load pll_3bitDiv_flat
cellname delete pll_3bitDiv -noprompt
cellname rename pll_3bitDiv_flat pll_3bitDiv
select top cell
extract path /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/pll_3bitDiv__pll_3bitDiv/magic_CC
extract all
ext2spice short none
ext2spice merge none
ext2spice cthresh 0.01
ext2spice subcircuits top on
ext2spice format ngspice
ext2spice -p /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/pll_3bitDiv__pll_3bitDiv/magic_CC -o /foss/designs/PROJECTS/cmos-pll-ihp-sg13g2/Combined_Design/design_data/pex/pll_3bitDiv__pll_3bitDiv/magic_CC/pll_3bitDiv.pex.spice
quit -noprompt